# Generated by Django 3.2.4 on 2021-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0002_auto_20211112_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletapp',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
