# Generated by Django 3.2.9 on 2021-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0003_toiletapp_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletapp',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
